env: DebugEnv
agent: RandomAgent  # or RandomAgent
seed: 0
n_trajectories: 2000
max_steps_per_episode: 15
train_interval: 1
save_interval: 100
eval_interval: 10
max_thread: -1


agent_kwargs:
  batch_size: 256
  actor_lr: 0.0003
  value_lr: 0.0003
  q_lr: 0.0003
  hidden_dims: [256, 256]
  discount: 0.99
  tau: 0.005
  target_period_update: 1
  reward_scale: 1.
  jit: False
