env: InvertedPendulumEnv
seed: 0
n_trajectories: 100000
max_thread: -1

agent_kwargs:
  batch_size: 256
  actor_lr: 3e-4
  value_lr: 3e-4
  q_lr: 3e-4
  hidden_dims: [256, 256]
  discount: 0.99
  tau: 0.005
  target_period_update: 1